### ISSUE TITLE
DataTables warning: table id=crud-list-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by pierrevdk** [SomeAverageDev/cozy-downloader#1]
Hi,

I just installed cozy-downloader on a cozy hosted by Cozy and I had this error: DataTables warning: table id=crud-list-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![capture du 2016-05-19 10 13 30](https://cloud.githubusercontent.com/assets/3509517/15387054/33c3a58a-1dab-11e6-90c5-0761d3c36bf3.png)

Pierre

**Comment by clochix** [comment]
I also hit this error the first time I used the application, but am unable to reproduce it.

Here are the server logs of this error:

```
GET / 200 3.379 ms - 4304
GET /vendor/bootstrap/css/bootstrap.min.css 200 1.352 ms - 121260
GET /vendor/styles/custom.css 200 0.461 ms - 198
GET /vendor/bootstrap/js/bootstrap.min.js 200 0.481 ms - 36868
GET /vendor/scripts/filesize.min.js 200 0.352 ms - 1349
GET /scripts/jquery.min.js 200 0.535 ms - 84345
GET /scripts/app.js 200 0.384 ms - 5625
GET /app/assets/icons/main_icon.png 200 0.688 ms - 6225
GET /downloads/list?_=1463645531450 - - ms - -
GET /downloads/list - - ms - -
GET /downloads/list - - ms - -
POST /downloads/new - - ms - -
GET /downloads/list - - ms - -
GET /downloads/list - - ms - -

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at /usr/local/cozy/apps/downloader/server/controllers/download.js:202:31
    at /usr/local/cozy/apps/downloader/node_modules/cozydb/lib/model.js:207:18
    at /usr/local/cozy/apps/downloader/node_modules/cozydb/lib/cozymodel.js:273:18
    at parseBody (/usr/local/cozy/apps/downloader/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/downloader/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
[2016-05-19 08:14:10:794] info - Cozy DB | download - all request creation...
[2016-05-19 08:14:10:831] info - Cozy DB | succeeded
[2016-05-19 08:14:10:832] info - Cozy DB | download - byStatus request creation...
[2016-05-19 08:14:10:881] info - Cozy DB | succeeded
[2016-05-19 08:14:10:881] info - Cozy DB | download - byUrl request creation...
[2016-05-19 08:14:10:909] info - Cozy DB | succeeded
[2016-05-19 08:14:10:909] info - Cozy DB | download - byFilename request creation...
[2016-05-19 08:14:10:935] info - Cozy DB | succeeded
[2016-05-19 08:14:10:935] info - Cozy DB | cozyinstance - all request creation...
[2016-05-19 08:14:10:966] info - Cozy DB | succeeded
[2016-05-19 08:14:10:966] info - Cozy DB | user - all request creation...
[2016-05-19 08:14:10:970] info - Cozy DB | succeeded
[2016-05-19 08:14:10:970] info - Cozy DB | cozyinstance - define indexes...
[2016-05-19 08:14:10:970] info - Cozy DB | download - define indexes...
Cozy downloader app listening at http://127.0.0.1:9251
```

**Comment by clochix** [comment]
I created a separate issue for the TypeError: #2
