### ISSUE TITLE
TypeError: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by clochix** [SomeAverageDev/cozy-downloader#2]
Seen in a user's logs:

```
url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at /usr/local/cozy/apps/downloader/server/controllers/download.js:202:31
    at /usr/local/cozy/apps/downloader/node_modules/cozydb/lib/model.js:207:18
    at /usr/local/cozy/apps/downloader/node_modules/cozydb/lib/cozymodel.js:273:18
    at parseBody (/usr/local/cozy/apps/downloader/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/downloader/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

(FTR, this user use Node 0.10.40).

/cc @pierrevdk

**Comment by SomeAverageDev** [comment]
I need to add a validator on the URL string to avoid empty value

**Comment by SomeAverageDev** [comment]
this should be fixed
